# Generated by Django 5.2.5 on 2025-08-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('ml', 'Masala'), ('gr', 'Ginger'), ('kl', 'Kiwi'), ('pl', 'Plain'), ('el', 'Elaichi')], max_length=2),
        ),
    ]
