# Generated by Django 5.2.5 on 2025-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_description_alter_page_image_alter_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('br', 'Brazil'), ('us', 'USA'), ('ca', 'Canada'), ('nz', 'New Zealand'), ('au', 'Australia')], max_length=2),
        ),
    ]
