# Generated by Django 5.2.5 on 2025-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='type',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='page',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
