# Generated by Django 5.2.5 on 2025-08-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_type_page_country_remove_page_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='pages.page')),
            ],
        ),
    ]
