# Generated by Django 5.2.5 on 2025-09-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_touristdestination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristdestination',
            name='image',
        ),
        migrations.CreateModel(
            name='TravelGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_level', models.CharField(choices=[('Safe', 'Safe'), ('Exercise Caution', 'Exercise Caution'), ('Not Safe', 'Not Safe')], max_length=50)),
                ('advice', models.TextField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideline', to='pages.page')),
            ],
        ),
    ]
