# Generated by Django 5.2.6 on 2025-09-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_touristdestination_image_travelguideline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='country',
            field=models.CharField(choices=[('br', 'gilgit'), ('us', 'USA'), ('ca', 'Canada'), ('nz', 'New Zealand'), ('au', 'Australia')], max_length=2),
        ),
    ]
