# Generated by Django 5.2.6 on 2025-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_page_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='country',
            field=models.CharField(choices=[('gl', 'Gilgit'), ('hz', 'Hunza'), ('sk', 'Skardu'), ('st', 'Swat Valley'), ('ak', 'Azad Kashmir')], max_length=2),
        ),
    ]
